export const categoriesToTransform = {
  "audio-and-video": "Audio and Video",
  "art-design-and-graphics": "Art, Design and Graphics",
  "business-and-finance": "Business and Finance",
  "education-and-productivity": "Education and Productivity",
  "social-media": "Social Media",
  "data-analysis-and-management": "Data Analysis and Management",
  "low-code-no-code": "Low-Code/No-Code",
  "audio-editing": "Audio editing",
  "startup-tools": "Startup Tools",
  "social-media-assistant": "Social Media Assistant",
  "e-commerce": "E-commerce",
  "code-assistant": "Code Assistant",
  "video-generator": "Video Generator",
  "general-writing": "General Writing",
  "email-assistant": "Email Assistant",
  "image-editing": "Image Editing",
  "logo-generator": "Logo Generator",
  "design-assistant": "Design Assistant",
  "image-generator": "Image Generator",
  "audio-editing": "Audio Editing",
  "personalized-videos": "Personalized Videos",
  "text-to-speech": "Text to Speech",
  "video-editing": "Video Editing",
  "code-assistant": "Code Assistant",
  "legal-assistant": "Legal Assistant",
  "text-to-speech": "Text To Speech",
  "customer-support": "Customer Support",
  "developer-tools": "Developer Tools",
  "life-assistant": "Life Assistant",
  "human-resources": "Human Resources",
  "search-engine": "Search Engine",
  "education-assistant": "Education Assistant",
  healthcare: "Healthcare",
  "fun-tools": "Fun Tools",
  "gift-ideas": "Gift Ideas",
};
